{{- if and .Values.jboss.ingress (or .Values.jboss.ingress.rules .Values.jboss.ingress.defaultBackend) }}
{{- with .Values.jboss.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "jboss.fullname" $ }}
  labels:
    {{- include "jboss.labels" $ | nindent 4 }}
  {{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .className }}
  {{- if .tls }}
  tls:
  {{- toYaml .tls | nindent 4 }}
  {{- end }}
  {{- if .rules }}
  rules:
  {{- toYaml .rules | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
